name: CI Test

on:
  push:
    branches:
      - main

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: Test action with sample catalog
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run wording replace action
        uses: ./
        with:
          aliases_json: test/aliases.json
          input_catalog_po: test/input.po
          output_catalog_po: test/output.po

      - name: Compare output with expected
        run: diff -u test/expected_output.po test/output.po
